[package]
name = "TorRouter"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "src/main.rs"
name = "TorRouter"


[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-socks = "0.5"
anyhow = "1.0"